{{- $root := . -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.requiredInfraDependencies.name }}
  namespace: {{ .Values.namespace.name }}
data:
  {{ range $settingKey, $settingValue := .Values.requiredInfraDependencies.values }}
  {{- $settingValue := trimPrefix "$" $settingValue }}
  {{- $actualSettingValue := pluck $settingValue $root.Values.infraSettings | first }}
  {{- $settingKey -}}: {{$actualSettingValue | quote}}
  {{ end }}
---