{{- range .Values.deployments }} #run through each deployment
{{ $currentDeployment := . }} #take current deployment
{{- if eq $currentDeployment.podLabels.type "web" }} #expose service port only for web applications.
apiVersion: v1
kind: Service
metadata:
  name: {{ $currentDeployment.name }}-service
  namespace: {{ $.Values.namespace.name }}
spec:
  type: NodePort
  selector:
    app: {{ $currentDeployment.name }} #this service is meant for the deployment
  ports:
    - protocol: TCP
      port: {{ $currentDeployment.podLabels.servicePort }} #service port
      targetPort: {{ $currentDeployment.podLabels.podPort }} #pod port
      nodePort: {{ $currentDeployment.podLabels.nodePort }} #node port
{{- end }}
---
{{- end }}